name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: keep lint but don't block deploy while you're finishing
      - name: Ruff (lint) but don't fail build
        uses: chartboost/ruff-action@v1
        with:
          args: --fix .
        continue-on-error: true

      - name: Deploy over SSH to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            # clone once if missing, otherwise update
            if [ ! -d /root/rag-homework/.git ]; then
              git clone https://github.com/${{ github.repository }} /root/rag-homework
            fi
            cd /root/rag-homework
            git fetch --all
            git reset --hard origin/main

            # keep your existing .env on EC2 (already working)
            # then (re)build & start
            docker compose up -d --build

            # show status
            docker ps
