name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    # don't block downstream jobs even if ruff finds issues
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Ruff (don't fail the build)
        uses: chartboost/ruff-action@v1
        with:
          # fix what it can, ignore long lines, but ALWAYS exit 0
          args: 'check . --select=E,F,I --ignore=E501 --fix --exit-zero'


  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build docker images (sanity)
        run: |
          docker build -t rag-backend ./backend
          docker build -t rag-frontend ./frontend

  deploy-ssh:
    needs: [build]   # or whatever job you lint/build in
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Deploy via SSH
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ~/rag-homework || git clone https://github.com/${{ github.repository }} ~/rag-homework && cd ~/rag-homework
            git fetch --all
            git reset --hard origin/main
            docker compose pull
            docker compose up -d --build
            docker ps
